const fs = require('fs');
const https = require('https');

function fetchJson(url) {
  return new Promise((resolve, reject) => {
    https.get(url, (res) => {
      let data = '';
      res.on('data', chunk => data += chunk);
      res.on('end', () => resolve(JSON.parse(data)));
    }).on('error', reject);
  });
}

async function run() {
  const url = 'https://arabic-bible-study-production.up.railway.app/api/v1/verses?book_id=1&chapter_num=11';
  const data = await fetchJson(url);
  let dbWords = [];
  data.data.forEach(v => {
      const clean = v.text_avd_ar.replace(/[.,:;«»!؟?]/g, '');
      dbWords.push(...clean.split(/\s+/).filter(w => w.trim().length > 0));
  });

  const userJson = [
{"word": "وكانت", "strongs": "H1961"},
{"word": "الارض", "strongs": "H776"},
{"word": "كلها", "strongs": "H3605"},
{"word": "لسانا", "strongs": "H8193"},
{"word": "واحدا", "strongs": "H259"},
{"word": "ولغة", "strongs": "H1697"},
{"word": "واحدة", "strongs": "H259"},
{"word": "وحدث", "strongs": "H1961"},
{"word": "في", "strongs": "H0"},
{"word": "ارتحالهم", "strongs": "H5265"},
{"word": "شرقا", "strongs": "H6924"},
{"word": "انهم", "strongs": "H0"},
{"word": "وجدوا", "strongs": "H4672"},
{"word": "بقعة", "strongs": "H1237"},
{"word": "في", "strongs": "H0"},
{"word": "ارض", "strongs": "H776"},
{"word": "شنعار", "strongs": "H8152"},
{"word": "وسكنوا", "strongs": "H3427"},
{"word": "هناك", "strongs": "H8033"},
{"word": "وقال", "strongs": "H559"},
{"word": "بعضهم", "strongs": "H376"},
{"word": "لبعض", "strongs": "H7453"},
{"word": "هلم", "strongs": "H3051"},
{"word": "نصنع", "strongs": "H3835"},
{"word": "لبنا", "strongs": "H3843"},
{"word": "ونشويه", "strongs": "H8313"},
{"word": "شيا", "strongs": "H8314"},
{"word": "فكان", "strongs": "H1961"},
{"word": "لهم", "strongs": "H0"},
{"word": "اللبن", "strongs": "H3843"},
{"word": "مكان", "strongs": "H0"},
{"word": "الحجر", "strongs": "H68"},
{"word": "وكان", "strongs": "H1961"},
{"word": "لهم", "strongs": "H0"},
{"word": "الحمر", "strongs": "H2564"},
{"word": "مكان", "strongs": "H0"},
{"word": "الطين", "strongs": "H2563"},
{"word": "وقالوا", "strongs": "H559"},
{"word": "هلم", "strongs": "H3051"},
{"word": "نبن", "strongs": "H1129"},
{"word": "لانفسنا", "strongs": "H0"},
{"word": "مدينة", "strongs": "H5892"},
{"word": "وبرجا", "strongs": "H4026"},
{"word": "راسه", "strongs": "H7218"},
{"word": "بالسماء", "strongs": "H8064"},
{"word": "ونصنع", "strongs": "H6213"},
{"word": "لانفسنا", "strongs": "H0"},
{"word": "اسما", "strongs": "H8034"},
{"word": "لئلا", "strongs": "H6435"},
{"word": "نتبدد", "strongs": "H6327"},
{"word": "على", "strongs": "H0"},
{"word": "وجه", "strongs": "H6440"},
{"word": "كل", "strongs": "H3605"},
{"word": "الارض", "strongs": "H776"},
{"word": "فنزل", "strongs": "H3381"},
{"word": "الرب", "strongs": "H3068"},
{"word": "لينظر", "strongs": "H7200"},
{"word": "المدينة", "strongs": "H5892"},
{"word": "والبرج", "strongs": "H4026"},
{"word": "اللذين", "strongs": "H0"},
{"word": "كان", "strongs": "H0"},
{"word": "بنو", "strongs": "H1121"},
{"word": "ادم", "strongs": "H120"},
{"word": "يبنونهما", "strongs": "H1129"},
{"word": "وقال", "strongs": "H559"},
{"word": "الرب", "strongs": "H3068"},
{"word": "هوذا", "strongs": "H2005"},
{"word": "شعب", "strongs": "H5971"},
{"word": "واحد", "strongs": "H259"},
{"word": "ولسان", "strongs": "H8193"},
{"word": "واحد", "strongs": "H259"},
{"word": "لجميعهم", "strongs": "H3605"},
{"word": "وهذا", "strongs": "H2088"},
{"word": "ابتداؤهم", "strongs": "H2490"},
{"word": "بالعمل", "strongs": "H6213"},
{"word": "والان", "strongs": "H6258"},
{"word": "لا", "strongs": "H3808"},
{"word": "يمتنع", "strongs": "H1219"},
{"word": "عليهم", "strongs": "H0"},
{"word": "كل", "strongs": "H3605"},
{"word": "ما", "strongs": "H0"},
{"word": "ينوون", "strongs": "H2161"},
{"word": "ان", "strongs": "H0"},
{"word": "يعملوه", "strongs": "H6213"},
{"word": "هلم", "strongs": "H3051"},
{"word": "ننزل", "strongs": "H3381"},
{"word": "ونبلبل", "strongs": "H1101"},
{"word": "هناك", "strongs": "H8033"},
{"word": "لسانهم", "strongs": "H8193"},
{"word": "حتى", "strongs": "H0"},
{"word": "لا", "strongs": "H3808"},
{"word": "يسمع", "strongs": "H8085"},
{"word": "بعضهم", "strongs": "H376"},
{"word": "لسان", "strongs": "H8193"},
{"word": "بعض", "strongs": "H7453"},
{"word": "فبددهم", "strongs": "H6327"},
{"word": "الرب", "strongs": "H3068"},
{"word": "من", "strongs": "H0"},
{"word": "هناك", "strongs": "H8033"},
{"word": "على", "strongs": "H0"},
{"word": "وجه", "strongs": "H6440"},
{"word": "كل", "strongs": "H3605"},
{"word": "الارض", "strongs": "H776"},
{"word": "فكفوا", "strongs": "H2308"},
{"word": "عن", "strongs": "H0"},
{"word": "بنيان", "strongs": "H1129"},
{"word": "المدينة", "strongs": "H5892"},
{"word": "لذلك", "strongs": "H5921"},
{"word": "دعي", "strongs": "H7121"},
{"word": "اسمها", "strongs": "H8034"},
{"word": "بابل", "strongs": "H894"},
{"word": "لان", "strongs": "H3588"},
{"word": "الرب", "strongs": "H3068"},
{"word": "هناك", "strongs": "H8033"},
{"word": "بلبل", "strongs": "H1101"},
{"word": "لسان", "strongs": "H8193"},
{"word": "كل", "strongs": "H3605"},
{"word": "الارض", "strongs": "H776"},
{"word": "ومن", "strongs": "H0"},
{"word": "هناك", "strongs": "H8033"},
{"word": "بددهم", "strongs": "H6327"},
{"word": "الرب", "strongs": "H3068"},
{"word": "على", "strongs": "H0"},
{"word": "وجه", "strongs": "H6440"},
{"word": "كل", "strongs": "H3605"},
{"word": "الارض", "strongs": "H776"},
{"word": "هذه", "strongs": "H428"},
{"word": "مواليد", "strongs": "H8435"},
{"word": "سام", "strongs": "H8035"},
{"word": "لما", "strongs": "H0"},
{"word": "كان", "strongs": "H1961"},
{"word": "سام", "strongs": "H8035"},
{"word": "ابن", "strongs": "H1121"},
{"word": "مئة", "strongs": "H3967"},
{"word": "سنة", "strongs": "H8141"},
{"word": "ولد", "strongs": "H3205"},
{"word": "ارفكشاد", "strongs": "H775"},
{"word": "بعد", "strongs": "H310"},
{"word": "الطوفان", "strongs": "H3999"},
{"word": "بسنتين", "strongs": "H8147"},
{"word": "وعاش", "strongs": "H2425"},
{"word": "سام", "strongs": "H8035"},
{"word": "بعد", "strongs": "H310"},
{"word": "ما", "strongs": "H0"},
{"word": "ولد", "strongs": "H3205"},
{"word": "ارفكشاد", "strongs": "H775"},
{"word": "خمس", "strongs": "H2568"},
{"word": "مئة", "strongs": "H3967"},
{"word": "سنة", "strongs": "H8141"},
{"word": "وولد", "strongs": "H3205"},
{"word": "بنين", "strongs": "H1121"},
{"word": "وبنات", "strongs": "H1323"},
{"word": "وعاش", "strongs": "H2425"},
{"word": "ارفكشاد", "strongs": "H775"},
{"word": "خمسا", "strongs": "H2568"},
{"word": "وثلاثين", "strongs": "H7970"},
{"word": "سنة", "strongs": "H8141"},
{"word": "وولد", "strongs": "H3205"},
{"word": "شالح", "strongs": "H7974"},
{"word": "وعاش", "strongs": "H2425"},
{"word": "ارفكشاد", "strongs": "H775"},
{"word": "بعد", "strongs": "H310"},
{"word": "ما", "strongs": "H0"},
{"word": "ولد", "strongs": "H3205"},
{"word": "شالح", "strongs": "H7974"},
{"word": "اربع", "strongs": "H702"},
{"word": "مئة", "strongs": "H3967"},
{"word": "وثلاث", "strongs": "H7969"},
{"word": "سنين", "strongs": "H8141"},
{"word": "وولد", "strongs": "H3205"},
{"word": "بنين", "strongs": "H1121"},
{"word": "وبنات", "strongs": "H1323"},
{"word": "وعاش", "strongs": "H2425"},
{"word": "شالح", "strongs": "H7974"},
{"word": "ثلاثين", "strongs": "H7970"},
{"word": "سنة", "strongs": "H8141"},
{"word": "وولد", "strongs": "H3205"},
{"word": "عابر", "strongs": "H5677"},
{"word": "وعاش", "strongs": "H2425"},
{"word": "شالح", "strongs": "H7974"},
{"word": "بعد", "strongs": "H310"},
{"word": "ما", "strongs": "H0"},
{"word": "ولد", "strongs": "H3205"},
{"word": "عابر", "strongs": "H5677"},
{"word": "اربع", "strongs": "H702"},
{"word": "مئة", "strongs": "H3967"},
{"word": "وثلاث", "strongs": "H7969"},
{"word": "سنين", "strongs": "H8141"},
{"word": "وولد", "strongs": "H3205"},
{"word": "بنين", "strongs": "H1121"},
{"word": "وبنات", "strongs": "H1323"},
{"word": "وعاش", "strongs": "H2425"},
{"word": "عابر", "strongs": "H5677"},
{"word": "اربعا", "strongs": "H702"},
{"word": "وثلاثين", "strongs": "H7970"},
{"word": "سنة", "strongs": "H8141"},
{"word": "وولد", "strongs": "H3205"},
{"word": "فالج", "strongs": "H6389"},
{"word": "وعاش", "strongs": "H2425"},
{"word": "عابر", "strongs": "H5677"},
{"word": "بعد", "strongs": "H310"},
{"word": "ما", "strongs": "H0"},
{"word": "ولد", "strongs": "H3205"},
{"word": "فالج", "strongs": "H6389"},
{"word": "اربع", "strongs": "H702"},
{"word": "مئة", "strongs": "H3967"},
{"word": "وثلاثين", "strongs": "H7970"},
{"word": "سنة", "strongs": "H8141"},
{"word": "وولد", "strongs": "H3205"},
{"word": "بنين", "strongs": "H1121"},
{"word": "وبنات", "strongs": "H1323"},
{"word": "وعاش", "strongs": "H2425"},
{"word": "فالج", "strongs": "H6389"},
{"word": "ثلاثين", "strongs": "H7970"},
{"word": "سنة", "strongs": "H8141"},
{"word": "وولد", "strongs": "H3205"},
{"word": "رعو", "strongs": "H7466"},
{"word": "وعاش", "strongs": "H2425"},
{"word": "فالج", "strongs": "H6389"},
{"word": "بعد", "strongs": "H310"},
{"word": "ما", "strongs": "H0"},
{"word": "ولد", "strongs": "H3205"},
{"word": "رعو", "strongs": "H7466"},
{"word": "مئتين", "strongs": "H3967"},
{"word": "وتسع", "strongs": "H8672"},
{"word": "سنين", "strongs": "H8141"},
{"word": "وولد", "strongs": "H3205"},
{"word": "بنين", "strongs": "H1121"},
{"word": "وبنات", "strongs": "H1323"},
{"word": "وعاش", "strongs": "H2425"},
{"word": "رعو", "strongs": "H7466"},
{"word": "اثنتين", "strongs": "H8147"},
{"word": "وثلاثين", "strongs": "H7970"},
{"word": "سنة", "strongs": "H8141"},
{"word": "وولد", "strongs": "H3205"},
{"word": "سروج", "strongs": "H8286"},
{"word": "وعاش", "strongs": "H2425"},
{"word": "رعو", "strongs": "H7466"},
{"word": "بعد", "strongs": "H310"},
{"word": "ما", "strongs": "H0"},
{"word": "ولد", "strongs": "H3205"},
{"word": "سروج", "strongs": "H8286"},
{"word": "مئتين", "strongs": "H3967"},
{"word": "وسبع", "strongs": "H7651"},
{"word": "سنين", "strongs": "H8141"},
{"word": "وولد", "strongs": "H3205"},
{"word": "بنين", "strongs": "H1121"},
{"word": "وبنات", "strongs": "H1323"},
{"word": "وعاش", "strongs": "H2425"},
{"word": "سروج", "strongs": "H8286"},
{"word": "ثلاثين", "strongs": "H7970"},
{"word": "سنة", "strongs": "H8141"},
{"word": "وولد", "strongs": "H3205"},
{"word": "ناحور", "strongs": "H5152"},
{"word": "وعاش", "strongs": "H2425"},
{"word": "سروج", "strongs": "H8286"},
{"word": "بعد", "strongs": "H310"},
{"word": "ما", "strongs": "H0"},
{"word": "ولد", "strongs": "H3205"},
{"word": "ناحور", "strongs": "H5152"},
{"word": "مئتين", "strongs": "H3967"},
{"word": "وسنتين", "strongs": "H8141"},
{"word": "وولد", "strongs": "H3205"},
{"word": "بنين", "strongs": "H1121"},
{"word": "وبنات", "strongs": "H1323"},
{"word": "وعاش", "strongs": "H2425"},
{"word": "ناحور", "strongs": "H5152"},
{"word": "تسعا", "strongs": "H8672"},
{"word": "وعشرين", "strongs": "H6242"},
{"word": "سنة", "strongs": "H8141"},
{"word": "وولد", "strongs": "H3205"},
{"word": "تارح", "strongs": "H8646"},
{"word": "وعاش", "strongs": "H2425"},
{"word": "ناحور", "strongs": "H5152"},
{"word": "بعد", "strongs": "H310"},
{"word": "ما", "strongs": "H0"},
{"word": "ولد", "strongs": "H3205"},
{"word": "تارح", "strongs": "H8646"},
{"word": "مئة", "strongs": "H3967"},
{"word": "وتسع", "strongs": "H8672"},
{"word": "عشرة", "strongs": "H6240"},
{"word": "سنة", "strongs": "H8141"},
{"word": "وولد", "strongs": "H3205"},
{"word": "بنين", "strongs": "H1121"},
{"word": "وبنات", "strongs": "H1323"},
{"word": "وعاش", "strongs": "H2425"},
{"word": "تارح", "strongs": "H8646"},
{"word": "سبعين", "strongs": "H7657"},
{"word": "سنة", "strongs": "H8141"},
{"word": "وولد", "strongs": "H3205"},
{"word": "ابرام", "strongs": "H87"},
{"word": "وناحور", "strongs": "H5152"},
{"word": "وهاران", "strongs": "H2039"},
{"word": "وهذه", "strongs": "H428"},
{"word": "مواليد", "strongs": "H8435"},
{"word": "تارح", "strongs": "H8646"},
{"word": "ولد", "strongs": "H3205"},
{"word": "تارح", "strongs": "H8646"},
{"word": "ابرام", "strongs": "H87"},
{"word": "وناحور", "strongs": "H5152"},
{"word": "وهاران", "strongs": "H2039"},
{"word": "وولد", "strongs": "H3205"},
{"word": "هاران", "strongs": "H2039"},
{"word": "لوطا", "strongs": "H3876"},
{"word": "ومات", "strongs": "H4191"},
{"word": "هاران", "strongs": "H2039"},
{"word": "قبل", "strongs": "H6440"},
{"word": "تارح", "strongs": "H8646"},
{"word": "ابيه", "strongs": "H1"},
{"word": "في", "strongs": "H0"},
{"word": "ارض", "strongs": "H776"},
{"word": "ميلاده", "strongs": "H4138"},
{"word": "في", "strongs": "H0"},
{"word": "اور", "strongs": "H218"},
{"word": "الكلدانيين", "strongs": "H3778"},
{"word": "واتخذ", "strongs": "H3947"},
{"word": "ابرام", "strongs": "H87"},
{"word": "وناحور", "strongs": "H5152"},
{"word": "لانفسهما", "strongs": "H0"},
{"word": "امراتين", "strongs": "H802"},
{"word": "اسم", "strongs": "H8034"},
{"word": "امراة", "strongs": "H802"},
{"word": "ابرام", "strongs": "H87"},
{"word": "ساراي", "strongs": "H8297"},
{"word": "واسم", "strongs": "H8034"},
{"word": "امراة", "strongs": "H802"},
{"word": "ناحور", "strongs": "H5152"},
{"word": "ملكة", "strongs": "H4435"},
{"word": "بنت", "strongs": "H1323"},
{"word": "هاران", "strongs": "H2039"},
{"word": "ابي", "strongs": "H1"},
{"word": "ملكة", "strongs": "H4435"},
{"word": "وابي", "strongs": "H1"},
{"word": "يسكة", "strongs": "H3252"},
{"word": "وكانت", "strongs": "H1961"},
{"word": "ساراي", "strongs": "H8297"},
{"word": "عاقرا", "strongs": "H6135"},
{"word": "ليس", "strongs": "H369"},
{"word": "لها", "strongs": "H0"},
{"word": "ولد", "strongs": "H2056"},
{"word": "واخذ", "strongs": "H3947"},
{"word": "تارح", "strongs": "H8646"},
{"word": "ابرام", "strongs": "H87"},
{"word": "ابنه", "strongs": "H1121"},
{"word": "ولوطا", "strongs": "H3876"},
{"word": "بن", "strongs": "H1121"},
{"word": "هاران", "strongs": "H2039"},
{"word": "ابن", "strongs": "H1121"},
{"word": "ابنه", "strongs": "H1121"},
{"word": "وساراي", "strongs": "H8297"},
{"word": "كنته", "strongs": "H3618"},
{"word": "امراة", "strongs": "H802"},
{"word": "ابرام", "strongs": "H87"},
{"word": "ابنه", "strongs": "H1121"},
{"word": "فخرجوا", "strongs": "H3318"},
{"word": "معا", "strongs": "H3162"},
{"word": "من", "strongs": "H0"},
{"word": "اور", "strongs": "H218"},
{"word": "الكلدانيين", "strongs": "H3778"},
{"word": "ليذهبوا", "strongs": "H1980"},
{"word": "الى", "strongs": "H0"},
{"word": "ارض", "strongs": "H776"},
{"word": "كنعان", "strongs": "H3667"},
{"word": "فاتوا", "strongs": "H935"},
{"word": "الى", "strongs": "H0"},
{"word": "حاران", "strongs": "H2771"},
{"word": "واقاموا", "strongs": "H3427"},
{"word": "هناك", "strongs": "H8033"},
{"word": "وكانت", "strongs": "H1961"},
{"word": "ايام", "strongs": "H3117"},
{"word": "تارح", "strongs": "H8646"},
{"word": "مئتين", "strongs": "H3967"},
{"word": "وخمس", "strongs": "H2568"},
{"word": "سنين", "strongs": "H8141"},
{"word": "ومات", "strongs": "H4191"},
{"word": "تارح", "strongs": "H8646"},
{"word": "في", "strongs": "H0"},
{"word": "حاران", "strongs": "H2771"}
];

  let result = [];
  let j = 0;
  
  for (let i = 0; i < dbWords.length; i++) {
      let wD = dbWords[i].replace(/[أإآ]/g, 'ا').replace(/ة/g, 'ه').replace(/ي/g, 'ى').replace(/ي/g, 'ي').replace(/ّ/g,'');
      
      let foundIndex = -1;
      for (let look = j; look < Math.min(j+5, userJson.length); look++) {
          let wJ = userJson[look].word.replace(/[أإآ]/g, 'ا').replace(/ة/g, 'ه').replace(/ي/g, 'ى').replace(/ي/g, 'ي');
          if (wD === wJ || wD.replace(/ي/g,'ى') === wJ.replace(/ي/g,'ى')) {
              foundIndex = look;
              break;
          }
      }
      
      if (foundIndex !== -1) {
          result.push({ word: dbWords[i], strongs: userJson[foundIndex].strongs });
          j = foundIndex + 1;
      } else {
          result.push({ word: dbWords[i], strongs: "H0" });
      }
  }

  // Also verify strongs validity
  const validStrongs = result.map(r => {
      if (r.strongs === "H0" || !/^H[1-9]\d{0,3}$/.test(r.strongs)) {
          return { ...r, strongs: "H0" };
      }
      return r;
  });

  fs.writeFileSync('Gen11_fixed.json', JSON.stringify(validStrongs, null, 2));
  console.log("Successfully created Gen11_fixed.json with exactly", validStrongs.length, "words.");
}
run();
