const fs = require('fs');
const https = require('https');

function fetchJson(url) {
  return new Promise((resolve, reject) => {
    https.get(url, (res) => {
      let data = '';
      res.on('data', chunk => data += chunk);
      res.on('end', () => resolve(JSON.parse(data)));
    }).on('error', reject);
  });
}

async function run() {
  const url = 'https://arabic-bible-study-production.up.railway.app/api/v1/verses?book_id=1&chapter_num=9';
  const data = await fetchJson(url);
  let dbWords = [];
  data.data.forEach(v => {
      const clean = v.text_avd_ar.replace(/[.,:;«»!؟?]/g, '');
      dbWords.push(...clean.split(/\s+/).filter(w => w.trim().length > 0));
  });

  const jsonText = `تكوين 9 وبارك الله نوحا وبنيه وقال لهم اثمروا واكثروا واملاوا الارض ولتكن خشيتكم ورهبتكم على كل حيوانات الارض وكل طيور السماء مع كل ما يدب على الارض وكل سمك البحر الى ايديكم دفعت كل دابة حية تكون لكم طعاما كعشب البقل اعطيتكم الجميع غير ان لحما بحياته دمه لا تاكلوه واطلب انا دمكم لانفسكم فقط من يد كل حيوان اطلبه ومن يد الانسان من يد الانسان اخيه اطلب نفس الانسان سافك دم الانسان بالانسان يسفك دمه لان الله على صورته عمل الانسان فاثمروا انتم واكثروا وتوالدوا في الارض وتكاثروا فيها وكلم الله نوحا وبنيه معه قائلا وها انا مقيم ميثاقي معكم ومع نسلكم من بعدكم ومع كل ذوات الانفس الحية التي معكم الطيور والبهائم وكل وحوش الارض التي معكم من جميع الخارجين من الفلك حتى كل حيوان الارض اقيم ميثاقي معكم فلا ينقرض كل ذي جسد ايضا بمياه الطوفان ولا يكون ايضا طوفان ليخرب الارض وقال الله هذه علامة الميثاق الذي انا واضعه بيني وبينكم وبين كل ذوات الانفس الحية التي معكم الى اجيال الدهر وضعت قوسي في السحاب فتكون علامة ميثاق بيني وبين الارض فيكون متى انشر سحابا على الارض وتظهر القوس في السحاب اني اذكر ميثاقي الذي بيني وبينكم وبين كل نفس حية في كل جسد فلا تكون ايضا المياه طوفانا لتهلك كل ذي جسد فمتى كانت القوس في السحاب ابصرها لاذكر ميثاقا ابديا بين الله وبين كل نفس حية في كل جسد على الارض وقال الله لنوح هذه علامة الميثاق الذي اقمته بيني وبين كل ذي جسد على الارض وكان بنو نوح الذين خرجوا من الفلك ساما وحاما ويافث وحام هو ابو كنعان هؤلاء الثلاثة هم بنو نوح ومن هؤلاء تشعبت كل الارض وابتدا نوح يكون فلاحا وغرس كرما وشرب من الخمر فسكر وتعرى داخل خبائه فابصر حام ابو كنعان عورة ابيه واخبر اخويه خارجا فاخذ سام ويافث الرداء ووضعاه على اكتافهما ومشيا الى الوراء وسترا عورة ابيهما ووجههما الى الوراء فلم يبصرا عورة ابيهما فلما استيقظ نوح من خمره علم ما فعل به ابنه الصغير فقال ملعون كنعان عبد العبيد يكون لاخوته وقال مبارك الرب اله سام وليكن كنعان عبدا لهم ليفتح الله ليافث فيسكن في خيام سام وليكن كنعان عبدا لهم وعاش نوح بعد الطوفان ثلاث مئة وخمسين سنة فكانت كل ايام نوح تسع مئة وخمسين سنة ومات`;
  // Using the raw JSON provided by the user
  const userJson = [
{"word": "تكوين", "strongs": "H0"},
{"word": "9", "strongs": "H0"},
{"word": "وبارك", "strongs": "H1288"},
{"word": "الله", "strongs": "H430"},
{"word": "نوحا", "strongs": "H5146"},
{"word": "وبنيه", "strongs": "H1121"},
{"word": "وقال", "strongs": "H559"},
{"word": "لهم", "strongs": "H0"},
{"word": "اثمروا", "strongs": "H6509"},
{"word": "واكثروا", "strongs": "H7235"},
{"word": "واملاوا", "strongs": "H4390"},
{"word": "الارض", "strongs": "H776"},
{"word": "ولتكن", "strongs": "H1961"},
{"word": "خشيتكم", "strongs": "H4172"},
{"word": "ورهبتكم", "strongs": "H2844"},
{"word": "على", "strongs": "H0"},
{"word": "كل", "strongs": "H3605"},
{"word": "حيوانات", "strongs": "H2416"},
{"word": "الارض", "strongs": "H776"},
{"word": "وكل", "strongs": "H3605"},
{"word": "طيور", "strongs": "H5775"},
{"word": "السماء", "strongs": "H8064"},
{"word": "مع", "strongs": "H0"},
{"word": "كل", "strongs": "H3605"},
{"word": "ما", "strongs": "H0"},
{"word": "يدب", "strongs": "H7430"},
{"word": "على", "strongs": "H0"},
{"word": "الارض", "strongs": "H127"},
{"word": "وكل", "strongs": "H3605"},
{"word": "سمك", "strongs": "H1710"},
{"word": "البحر", "strongs": "H3220"},
{"word": "الى", "strongs": "H0"},
{"word": "ايديكم", "strongs": "H3027"},
{"word": "دفعت", "strongs": "H5414"},
{"word": "كل", "strongs": "H3605"},
{"word": "دابة", "strongs": "H7431"},
{"word": "حية", "strongs": "H2416"},
{"word": "تكون", "strongs": "H1961"},
{"word": "لكم", "strongs": "H0"},
{"word": "طعاما", "strongs": "H402"},
{"word": "كعشب", "strongs": "H6212"},
{"word": "البقل", "strongs": "H3418"},
{"word": "اعطيتكم", "strongs": "H5414"},
{"word": "الجميع", "strongs": "H3605"},
{"word": "غير", "strongs": "H3808"},
{"word": "ان", "strongs": "H0"},
{"word": "لحما", "strongs": "H1320"},
{"word": "بحياته", "strongs": "H5315"},
{"word": "دمه", "strongs": "H1818"},
{"word": "لا", "strongs": "H3808"},
{"word": "تاكلوه", "strongs": "H398"},
{"word": "واطلب", "strongs": "H1875"},
{"word": "انا", "strongs": "H0"},
{"word": "دمكم", "strongs": "H1818"},
{"word": "لانفسكم", "strongs": "H5315"},
{"word": "فقط", "strongs": "H0"},
{"word": "من", "strongs": "H0"},
{"word": "يد", "strongs": "H3027"},
{"word": "كل", "strongs": "H3605"},
{"word": "حيوان", "strongs": "H2416"},
{"word": "اطلبه", "strongs": "H1875"},
{"word": "ومن", "strongs": "H0"},
{"word": "يد", "strongs": "H3027"},
{"word": "الانسان", "strongs": "H120"},
{"word": "من", "strongs": "H0"},
{"word": "يد", "strongs": "H3027"},
{"word": "الانسان", "strongs": "H376"},
{"word": "اخيه", "strongs": "H251"},
{"word": "اطلب", "strongs": "H1875"},
{"word": "نفس", "strongs": "H5315"},
{"word": "الانسان", "strongs": "H120"},
{"word": "سافك", "strongs": "H8210"},
{"word": "دم", "strongs": "H1818"},
{"word": "الانسان", "strongs": "H120"},
{"word": "بالانسان", "strongs": "H120"},
{"word": "يسفك", "strongs": "H8210"},
{"word": "دمه", "strongs": "H1818"},
{"word": "لان", "strongs": "H3588"},
{"word": "الله", "strongs": "H430"},
{"word": "على", "strongs": "H0"},
{"word": "صورته", "strongs": "H6754"},
{"word": "عمل", "strongs": "H6213"},
{"word": "الانسان", "strongs": "H120"},
{"word": "فاثمروا", "strongs": "H6509"},
{"word": "انتم", "strongs": "H859"},
{"word": "واكثروا", "strongs": "H7235"},
{"word": "وتوالدوا", "strongs": "H8317"},
{"word": "في", "strongs": "H0"},
{"word": "الارض", "strongs": "H776"},
{"word": "وتكاثروا", "strongs": "H7235"},
{"word": "فيها", "strongs": "H0"},
{"word": "وكلم", "strongs": "H559"},
{"word": "الله", "strongs": "H430"},
{"word": "نوحا", "strongs": "H5146"},
{"word": "وبنيه", "strongs": "H1121"},
{"word": "معه", "strongs": "H854"},
{"word": "قائلا", "strongs": "H559"},
{"word": "وها", "strongs": "H2005"},
{"word": "انا", "strongs": "H589"},
{"word": "مقيم", "strongs": "H6965"},
{"word": "ميثاقي", "strongs": "H1285"},
{"word": "معكم", "strongs": "H854"},
{"word": "ومع", "strongs": "H854"},
{"word": "نسلكم", "strongs": "H2233"},
{"word": "من", "strongs": "H0"},
{"word": "بعدكم", "strongs": "H310"},
{"word": "ومع", "strongs": "H854"},
{"word": "كل", "strongs": "H3605"},
{"word": "ذوات", "strongs": "H0"},
{"word": "الانفس", "strongs": "H5315"},
{"word": "الحية", "strongs": "H2416"},
{"word": "التي", "strongs": "H834"},
{"word": "معكم", "strongs": "H854"},
{"word": "الطيور", "strongs": "H5775"},
{"word": "والبهائم", "strongs": "H929"},
{"word": "وكل", "strongs": "H3605"},
{"word": "وحوش", "strongs": "H2416"},
{"word": "الارض", "strongs": "H776"},
{"word": "التي", "strongs": "H834"},
{"word": "معكم", "strongs": "H854"},
{"word": "من", "strongs": "H0"},
{"word": "جميع", "strongs": "H3605"},
{"word": "الخارجين", "strongs": "H3318"},
{"word": "من", "strongs": "H0"},
{"word": "الفلك", "strongs": "H8392"},
{"word": "حتى", "strongs": "H5704"},
{"word": "كل", "strongs": "H3605"},
{"word": "حيوان", "strongs": "H2416"},
{"word": "الارض", "strongs": "H776"},
{"word": "اقيم", "strongs": "H6965"},
{"word": "ميثاقي", "strongs": "H1285"},
{"word": "معكم", "strongs": "H854"},
{"word": "فلا", "strongs": "H3808"},
{"word": "ينقرض", "strongs": "H3772"},
{"word": "كل", "strongs": "H3605"},
{"word": "ذي", "strongs": "H0"},
{"word": "جسد", "strongs": "H1320"},
{"word": "ايضا", "strongs": "H5750"},
{"word": "بمياه", "strongs": "H4325"},
{"word": "الطوفان", "strongs": "H3999"},
{"word": "ولا", "strongs": "H3808"},
{"word": "يكون", "strongs": "H1961"},
{"word": "ايضا", "strongs": "H5750"},
{"word": "طوفان", "strongs": "H3999"},
{"word": "ليخرب", "strongs": "H7843"},
{"word": "الارض", "strongs": "H776"},
{"word": "وقال", "strongs": "H559"},
{"word": "الله", "strongs": "H430"},
{"word": "هذه", "strongs": "H2063"},
{"word": "علامة", "strongs": "H226"},
{"word": "الميثاق", "strongs": "H1285"},
{"word": "الذي", "strongs": "H834"},
{"word": "انا", "strongs": "H589"},
{"word": "واضعه", "strongs": "H5414"},
{"word": "بيني", "strongs": "H996"},
{"word": "وبينكم", "strongs": "H996"},
{"word": "وبين", "strongs": "H996"},
{"word": "كل", "strongs": "H3605"},
{"word": "ذوات", "strongs": "H0"},
{"word": "الانفس", "strongs": "H5315"},
{"word": "الحية", "strongs": "H2416"},
{"word": "التي", "strongs": "H834"},
{"word": "معكم", "strongs": "H854"},
{"word": "الى", "strongs": "H0"},
{"word": "اجيال", "strongs": "H1755"},
{"word": "الدهر", "strongs": "H5769"},
{"word": "وضعت", "strongs": "H5414"},
{"word": "قوسي", "strongs": "H7198"},
{"word": "في", "strongs": "H0"},
{"word": "السحاب", "strongs": "H6051"},
{"word": "فتكون", "strongs": "H1961"},
{"word": "علامة", "strongs": "H226"},
{"word": "ميثاق", "strongs": "H1285"},
{"word": "بيني", "strongs": "H996"},
{"word": "وبين", "strongs": "H996"},
{"word": "الارض", "strongs": "H776"},
{"word": "فيكون", "strongs": "H1961"},
{"word": "متى", "strongs": "H6045"},
{"word": "انشر", "strongs": "H6049"},
{"word": "سحابا", "strongs": "H6051"},
{"word": "على", "strongs": "H0"},
{"word": "الارض", "strongs": "H776"},
{"word": "وتظهر", "strongs": "H7200"},
{"word": "القوس", "strongs": "H7198"},
{"word": "في", "strongs": "H0"},
{"word": "السحاب", "strongs": "H6051"},
{"word": "اني", "strongs": "H0"},
{"word": "اذكر", "strongs": "H2142"},
{"word": "ميثاقي", "strongs": "H1285"},
{"word": "الذي", "strongs": "H834"},
{"word": "بيني", "strongs": "H996"},
{"word": "وبينكم", "strongs": "H996"},
{"word": "وبين", "strongs": "H996"},
{"word": "كل", "strongs": "H3605"},
{"word": "نفس", "strongs": "H5315"},
{"word": "حية", "strongs": "H2416"},
{"word": "في", "strongs": "H0"},
{"word": "كل", "strongs": "H3605"},
{"word": "جسد", "strongs": "H1320"},
{"word": "فلا", "strongs": "H3808"},
{"word": "تكون", "strongs": "H1961"},
{"word": "ايضا", "strongs": "H5750"},
{"word": "المياه", "strongs": "H4325"},
{"word": "طوفانا", "strongs": "H3999"},
{"word": "لتهلك", "strongs": "H7843"},
{"word": "كل", "strongs": "H3605"},
{"word": "ذي", "strongs": "H0"},
{"word": "جسد", "strongs": "H1320"},
{"word": "فمتى", "strongs": "H1961"},
{"word": "كانت", "strongs": "H1961"},
{"word": "القوس", "strongs": "H7198"},
{"word": "في", "strongs": "H0"},
{"word": "السحاب", "strongs": "H6051"},
{"word": "ابصرها", "strongs": "H7200"},
{"word": "لاذكر", "strongs": "H2142"},
{"word": "ميثاقا", "strongs": "H1285"},
{"word": "ابديا", "strongs": "H5769"},
{"word": "بين", "strongs": "H996"},
{"word": "الله", "strongs": "H430"},
{"word": "وبين", "strongs": "H996"},
{"word": "كل", "strongs": "H3605"},
{"word": "نفس", "strongs": "H5315"},
{"word": "حية", "strongs": "H2416"},
{"word": "في", "strongs": "H0"},
{"word": "كل", "strongs": "H3605"},
{"word": "جسد", "strongs": "H1320"},
{"word": "على", "strongs": "H0"},
{"word": "الارض", "strongs": "H776"},
{"word": "وقال", "strongs": "H559"},
{"word": "الله", "strongs": "H430"},
{"word": "لنوح", "strongs": "H5146"},
{"word": "هذه", "strongs": "H2063"},
{"word": "علامة", "strongs": "H226"},
{"word": "الميثاق", "strongs": "H1285"},
{"word": "الذي", "strongs": "H834"},
{"word": "اقمته", "strongs": "H6965"},
{"word": "بيني", "strongs": "H996"},
{"word": "وبين", "strongs": "H996"},
{"word": "كل", "strongs": "H3605"},
{"word": "ذي", "strongs": "H0"},
{"word": "جسد", "strongs": "H1320"},
{"word": "على", "strongs": "H0"},
{"word": "الارض", "strongs": "H776"},
{"word": "وكان", "strongs": "H1961"},
{"word": "بنو", "strongs": "H1121"},
{"word": "نوح", "strongs": "H5146"},
{"word": "الذين", "strongs": "H834"},
{"word": "خرجوا", "strongs": "H3318"},
{"word": "من", "strongs": "H0"},
{"word": "الفلك", "strongs": "H8392"},
{"word": "ساما", "strongs": "H8035"},
{"word": "وحاما", "strongs": "H2526"},
{"word": "ويافث", "strongs": "H3315"},
{"word": "وحام", "strongs": "H2526"},
{"word": "هو", "strongs": "H1931"},
{"word": "ابو", "strongs": "H1"},
{"word": "كنعان", "strongs": "H3667"},
{"word": "هؤلاء", "strongs": "H428"},
{"word": "الثلاثة", "strongs": "H7969"},
{"word": "هم", "strongs": "H0"},
{"word": "بنو", "strongs": "H1121"},
{"word": "نوح", "strongs": "H5146"},
{"word": "ومن", "strongs": "H4480"},
{"word": "هؤلاء", "strongs": "H428"},
{"word": "تشعبت", "strongs": "H5310"},
{"word": "كل", "strongs": "H3605"},
{"word": "الارض", "strongs": "H776"},
{"word": "وابتدا", "strongs": "H2490"},
{"word": "نوح", "strongs": "H5146"},
{"word": "يكون", "strongs": "H376"},
{"word": "فلاحا", "strongs": "H127"},
{"word": "وغرس", "strongs": "H5193"},
{"word": "كرما", "strongs": "H3754"},
{"word": "وشرب", "strongs": "H8354"},
{"word": "من", "strongs": "H0"},
{"word": "الخمر", "strongs": "H3196"},
{"word": "فسكر", "strongs": "H7937"},
{"word": "وتعرى", "strongs": "H1540"},
{"word": "داخل", "strongs": "H8432"},
{"word": "خبائه", "strongs": "H168"},
{"word": "فابصر", "strongs": "H7200"},
{"word": "حام", "strongs": "H2526"},
{"word": "ابو", "strongs": "H1"},
{"word": "كنعان", "strongs": "H3667"},
{"word": "عورة", "strongs": "H6172"},
{"word": "ابيه", "strongs": "H1"},
{"word": "واخبر", "strongs": "H5046"},
{"word": "اخويه", "strongs": "H251"},
{"word": "خارجا", "strongs": "H2351"},
{"word": "فاخذ", "strongs": "H3947"},
{"word": "سام", "strongs": "H8035"},
{"word": "ويافث", "strongs": "H3315"},
{"word": "الرداء", "strongs": "H8071"},
{"word": "ووضعاه", "strongs": "H7760"},
{"word": "على", "strongs": "H0"},
{"word": "اكتافهما", "strongs": "H7926"},
{"word": "ومشيا", "strongs": "H1980"},
{"word": "الى", "strongs": "H0"},
{"word": "الوراء", "strongs": "H322"},
{"word": "وسترا", "strongs": "H3680"},
{"word": "عورة", "strongs": "H6172"},
{"word": "ابيهما", "strongs": "H1"},
{"word": "ووجههما", "strongs": "H6440"},
{"word": "الى", "strongs": "H0"},
{"word": "الوراء", "strongs": "H322"},
{"word": "فلم", "strongs": "H3808"},
{"word": "يبصرا", "strongs": "H7200"},
{"word": "عورة", "strongs": "H6172"},
{"word": "ابيهما", "strongs": "H1"},
{"word": "فلما", "strongs": "H0"},
{"word": "استيقظ", "strongs": "H3364"},
{"word": "نوح", "strongs": "H5146"},
{"word": "من", "strongs": "H0"},
{"word": "خمره", "strongs": "H3196"},
{"word": "علم", "strongs": "H3045"},
{"word": "ما", "strongs": "H834"},
{"word": "فعل", "strongs": "H6213"},
{"word": "به", "strongs": "H0"},
{"word": "ابنه", "strongs": "H1121"},
{"word": "الصغير", "strongs": "H6996"},
{"word": "فقال", "strongs": "H559"},
{"word": "ملعون", "strongs": "H779"},
{"word": "كنعان", "strongs": "H3667"},
{"word": "عبد", "strongs": "H5650"},
{"word": "العبيد", "strongs": "H5650"},
{"word": "يكون", "strongs": "H1961"},
{"word": "لاخوته", "strongs": "H251"},
{"word": "وقال", "strongs": "H559"},
{"word": "مبارك", "strongs": "H1288"},
{"word": "الرب", "strongs": "H3068"},
{"word": "اله", "strongs": "H430"},
{"word": "سام", "strongs": "H8035"},
{"word": "وليكن", "strongs": "H1961"},
{"word": "كنعان", "strongs": "H3667"},
{"word": "عبدا", "strongs": "H5650"},
{"word": "لهم", "strongs": "H0"},
{"word": "ليفتح", "strongs": "H6601"},
{"word": "الله", "strongs": "H430"},
{"word": "ليافث", "strongs": "H3315"},
{"word": "فيسكن", "strongs": "H7931"},
{"word": "في", "strongs": "H0"},
{"word": "خيام", "strongs": "H168"},
{"word": "سام", "strongs": "H8035"},
{"word": "وليكن", "strongs": "H1961"},
{"word": "كنعان", "strongs": "H3667"},
{"word": "عبدا", "strongs": "H5650"},
{"word": "لهم", "strongs": "H0"},
{"word": "وعاش", "strongs": "H2425"},
{"word": "نوح", "strongs": "H5146"},
{"word": "بعد", "strongs": "H310"},
{"word": "الطوفان", "strongs": "H3999"},
{"word": "ثلاث", "strongs": "H7969"},
{"word": "مئة", "strongs": "H3967"},
{"word": "وخمسين", "strongs": "H2572"},
{"word": "سنة", "strongs": "H8141"},
{"word": "فكانت", "strongs": "H1961"},
{"word": "كل", "strongs": "H3605"},
{"word": "ايام", "strongs": "H3117"},
{"word": "نوح", "strongs": "H5146"},
{"word": "تسع", "strongs": "H8672"},
{"word": "مئة", "strongs": "H3967"},
{"word": "وخمسين", "strongs": "H2572"},
{"word": "سنة", "strongs": "H8141"},
{"word": "ومات", "strongs": "H4191"}
];

  let result = [];
  let j = 0;
  // skip تكوين 9
  if (userJson[0].word === 'تكوين' && userJson[1].word === '9') {
      j = 2;
  }
  
  for (let i = 0; i < dbWords.length; i++) {
      let wD = dbWords[i].replace(/[أإآ]/g, 'ا').replace(/ة/g, 'ه').replace(/ي/g, 'ى').replace(/ي/g, 'ي').replace(/ّ/g,'');
      
      // Look for match in next 5 words of json
      let foundIndex = -1;
      for (let look = j; look < Math.min(j+5, userJson.length); look++) {
          let wJ = userJson[look].word.replace(/[أإآ]/g, 'ا').replace(/ة/g, 'ه').replace(/ي/g, 'ى').replace(/ي/g, 'ي');
          if (wD === wJ || wD.replace(/ي/g,'ى') === wJ.replace(/ي/g,'ى')) {
              foundIndex = look;
              break;
          }
      }
      
      if (foundIndex !== -1) {
          result.push({ word: dbWords[i], strongs: userJson[foundIndex].strongs });
          j = foundIndex + 1; // advance j past the matched word
      } else {
          // If we couldn't find a match, just append the DB word with H0
          result.push({ word: dbWords[i], strongs: "H0" });
      }
  }

  fs.writeFileSync('Gen9_fixed.json', JSON.stringify(result, null, 2));
  console.log("Successfully created Gen9_fixed.json with exactly", result.length, "words.");
}
run();
