const list1 = [
{"word": "يهوذا", "strongs": "G2455"},
{"word": "عبد", "strongs": "G1401"},
{"word": "يسوع", "strongs": "G2424"},
{"word": "المسيح", "strongs": "G5547"},
{"word": "واخو", "strongs": "G80"},
{"word": "يعقوب", "strongs": "G2385"},
{"word": "الى", "strongs": "G1519"},
{"word": "المدعوين", "strongs": "G2822"},
{"word": "المقدسين", "strongs": "G37"},
{"word": "في", "strongs": "G1722"},
{"word": "الله", "strongs": "G2316"},
{"word": "الاب", "strongs": "G396"},
{"word": "والمحفوظين", "strongs": "G5083"},
{"word": "ليسوع", "strongs": "G2424"},
{"word": "المسيح", "strongs": "G5547"},
{"word": "لتكثر", "strongs": "G4129"},
{"word": "لكم", "strongs": "G0"},
{"word": "الرحمة", "strongs": "G1656"},
{"word": "والسلام", "strongs": "G1515"},
{"word": "والمحبة", "strongs": "G26"},
{"word": "ايها", "strongs": "G0"},
{"word": "الاحباء", "strongs": "G27"},
{"word": "اذ", "strongs": "G0"},
{"word": "كنت", "strongs": "G0"},
{"word": "اصنع", "strongs": "G4160"},
{"word": "كل", "strongs": "G3956"},
{"word": "جهد", "strongs": "G4710"},
{"word": "لاكتب", "strongs": "G1125"},
{"word": "اليكم", "strongs": "G0"},
{"word": "عن", "strongs": "G4012"},
{"word": "الخلاص", "strongs": "G4991"},
{"word": "المشترك", "strongs": "G2839"},
{"word": "اضطررت", "strongs": "G318"},
{"word": "ان", "strongs": "G0"},
{"word": "اكتب", "strongs": "G1125"},
{"word": "اليكم", "strongs": "G0"},
{"word": "واعظا", "strongs": "G3870"},
{"word": "ان", "strongs": "G0"},
{"word": "تجتهدوا", "strongs": "G1864"},
{"word": "لاجل", "strongs": "G5228"},
{"word": "الايمان", "strongs": "G4102"},
{"word": "المسلم", "strongs": "G3860"},
{"word": "مرة", "strongs": "G530"},
{"word": "للقديسين", "strongs": "G40"},
{"word": "لانه", "strongs": "G1063"},
{"word": "دخل", "strongs": "G3921"},
{"word": "خلسة", "strongs": "G3921"},
{"word": "اناس", "strongs": "G444"},
{"word": "قد", "strongs": "G0"},
{"word": "كتبوا", "strongs": "G4270"},
{"word": "منذ", "strongs": "G3819"},
{"word": "القديم", "strongs": "G3819"},
{"word": "لهذه", "strongs": "G5124"},
{"word": "الدينونة", "strongs": "G2917"},
{"word": "فجار", "strongs": "G765"},
{"word": "يحولون", "strongs": "G3346"},
{"word": "نعمة", "strongs": "G5485"},
{"word": "الهنا", "strongs": "G2316"},
{"word": "الى", "strongs": "G1519"},
{"word": "الدعارة", "strongs": "G766"},
{"word": "وينكرون", "strongs": "G720"},
{"word": "السيد", "strongs": "G1203"},
{"word": "الوحيد", "strongs": "G3441"},
{"word": "الله", "strongs": "G2316"},
{"word": "وربنا", "strongs": "G2962"},
{"word": "يسوع", "strongs": "G2424"},
{"word": "المسيح", "strongs": "G5547"},
{"word": "فاريد", "strongs": "G1014"},
{"word": "ان", "strongs": "G0"},
{"word": "اذكركم", "strongs": "G5279"},
{"word": "ولو", "strongs": "G2539"},
{"word": "علمتم", "strongs": "G1492"},
{"word": "هذا", "strongs": "G5124"},
{"word": "مرة", "strongs": "G530"},
{"word": "ان", "strongs": "G3754"},
{"word": "الرب", "strongs": "G2962"},
{"word": "بعدما", "strongs": "G0"},
{"word": "خلص", "strongs": "G4982"},
{"word": "الشعب", "strongs": "G2992"},
{"word": "من", "strongs": "G1537"},
{"word": "ارض", "strongs": "G1093"},
{"word": "مصر", "strongs": "G125"},
{"word": "اهلك", "strongs": "G622"},
{"word": "ايضا", "strongs": "G1208"},
{"word": "الذين", "strongs": "G3588"},
{"word": "لم", "strongs": "G3361"},
{"word": "يؤمنوا", "strongs": "G4100"},
{"word": "والملائكة", "strongs": "G32"},
{"word": "الذين", "strongs": "G3588"},
{"word": "لم", "strongs": "G3361"},
{"word": "يحفظوا", "strongs": "G5083"},
{"word": "رياستهم", "strongs": "G746"},
{"word": "بل", "strongs": "G235"},
{"word": "تركوا", "strongs": "G620"},
{"word": "مسكنهم", "strongs": "G3613"},
{"word": "حفظهم", "strongs": "G5083"},
{"word": "الى", "strongs": "G1519"},
{"word": "دينونة", "strongs": "G2920"},
{"word": "اليوم", "strongs": "G2250"},
{"word": "العظيم", "strongs": "G3173"},
{"word": "بقيود", "strongs": "G1199"},
{"word": "ابدية", "strongs": "G126"},
{"word": "تحت", "strongs": "G5259"},
{"word": "الظلام", "strongs": "G2217"},
{"word": "كما", "strongs": "G5613"},
{"word": "ان", "strongs": "G0"},
{"word": "سدوم", "strongs": "G4670"},
{"word": "وعمورة", "strongs": "G1111"},
{"word": "والمدن", "strongs": "G4172"},
{"word": "التي", "strongs": "G3588"},
{"word": "حولهما", "strongs": "G4012"},
{"word": "اذ", "strongs": "G5613"},
{"word": "زنت", "strongs": "G1608"},
{"word": "على", "strongs": "G5158"},
{"word": "طريق", "strongs": "G5158"},
{"word": "مثلهما", "strongs": "G5127"},
{"word": "ومضت", "strongs": "G565"},
{"word": "وراء", "strongs": "G3694"},
{"word": "جسد", "strongs": "G4561"},
{"word": "اخر", "strongs": "G2087"},
{"word": "جعلت", "strongs": "G4295"},
{"word": "عبرة", "strongs": "G1164"},
{"word": "مكابدة", "strongs": "G5254"},
{"word": "عقاب", "strongs": "G1349"},
{"word": "نار", "strongs": "G4442"},
{"word": "ابدية", "strongs": "G166"},
{"word": "ولكن", "strongs": "G3676"},
{"word": "كذلك", "strongs": "G3668"},
{"word": "هؤلاء", "strongs": "G3778"},
{"word": "ايضا", "strongs": "G2532"},
{"word": "الحالمون", "strongs": "G1797"},
{"word": "ينجسون", "strongs": "G3392"},
{"word": "الجسد", "strongs": "G4561"},
{"word": "ويتهاونون", "strongs": "G114"},
{"word": "بالسيادة", "strongs": "G2963"},
{"word": "ويفترون", "strongs": "G987"},
{"word": "على", "strongs": "G0"},
{"word": "ذوي", "strongs": "G1391"},
{"word": "الامجاد", "strongs": "G1391"},
{"word": "واما", "strongs": "G1161"},
{"word": "ميخائيل", "strongs": "G3413"},
{"word": "رئيس", "strongs": "G743"},
{"word": "الملائكة", "strongs": "G743"},
{"word": "فلما", "strongs": "G3753"},
{"word": "خاصم", "strongs": "G1252"},
{"word": "ابليس", "strongs": "G1228"},
{"word": "وحاجه", "strongs": "G1252"},
{"word": "عن", "strongs": "G4012"},
{"word": "جسد", "strongs": "G4983"},
{"word": "موسى", "strongs": "G3475"},
{"word": "لم", "strongs": "G3756"},
{"word": "يجسر", "strongs": "G5111"},
{"word": "ان", "strongs": "G0"},
{"word": "يورد", "strongs": "G2018"},
{"word": "حكم", "strongs": "G2920"},
{"word": "افتراء", "strongs": "G988"},
{"word": "بل", "strongs": "G235"},
{"word": "قال", "strongs": "G2036"},
{"word": "لينتهرك", "strongs": "G2008"},
{"word": "الرب", "strongs": "G2962"},
{"word": "ولكن", "strongs": "G1161"},
{"word": "هؤلاء", "strongs": "G3778"},
{"word": "يفترون", "strongs": "G987"},
{"word": "على", "strongs": "G0"},
{"word": "ما", "strongs": "G3745"},
{"word": "لا", "strongs": "G3756"},
{"word": "يعلمون", "strongs": "G1492"},
{"word": "واما", "strongs": "G1161"},
{"word": "ما", "strongs": "G3745"},
{"word": "يفهمونه", "strongs": "G1987"},
{"word": "بالطبيعة", "strongs": "G5446"},
{"word": "كالحيوانات", "strongs": "G2241"},
{"word": "غير", "strongs": "G249"},
{"word": "الناطقة", "strongs": "G249"},
{"word": "ففي", "strongs": "G1722"},
{"word": "ذلك", "strongs": "G5125"},
{"word": "يفسدون", "strongs": "G5351"},
{"word": "ويل", "strongs": "G3759"},
{"word": "لهم", "strongs": "G846"},
{"word": "لانهم", "strongs": "G3754"},
{"word": "سلكوا", "strongs": "G4198"},
{"word": "في", "strongs": "G1722"},
{"word": "طريق", "strongs": "G3598"},
{"word": "قايين", "strongs": "G2564"},
{"word": "وانصبوا", "strongs": "G1632"},
{"word": "الى", "strongs": "G1519"},
{"word": "ضلالة", "strongs": "G4106"},
{"word": "بلعام", "strongs": "G903"},
{"word": "لاجل", "strongs": "G1752"},
{"word": "اجرة", "strongs": "G3408"},
{"word": "وهلكوا", "strongs": "G622"},
{"word": "في", "strongs": "G1722"},
{"word": "مشاجرة", "strongs": "G485"},
{"word": "قورح", "strongs": "G2879"},
{"word": "هؤلاء", "strongs": "G3778"},
{"word": "صخور", "strongs": "G4694"},
{"word": "في", "strongs": "G1722"},
{"word": "ولائمكم", "strongs": "G26"},
{"word": "المحبية", "strongs": "G26"},
{"word": "صانعين", "strongs": "G4910"},
{"word": "ولائم", "strongs": "G4910"},
{"word": "معا", "strongs": "G0"},
{"word": "بلا", "strongs": "G870"},
{"word": "خوف", "strongs": "G870"},
{"word": "راعين", "strongs": "G4165"},
{"word": "انفسهم", "strongs": "G1438"},
{"word": "غيوم", "strongs": "G3507"},
{"word": "بلا", "strongs": "G3756"},
{"word": "ماء", "strongs": "G5204"},
{"word": "تحملها", "strongs": "G3911"},
{"word": "الرياح", "strongs": "G417"},
{"word": "اشجار", "strongs": "G1186"},
{"word": "خريفية", "strongs": "G5352"},
{"word": "بلا", "strongs": "G171"},
{"word": "ثمر", "strongs": "G2593"},
{"word": "ميتة", "strongs": "G593"},
{"word": "مضاعفا", "strongs": "G1364"},
{"word": "مقتلعة", "strongs": "G1610"},
{"word": "امواج", "strongs": "G2949"},
{"word": "بحر", "strongs": "G2281"},
{"word": "هائجة", "strongs": "G66"},
{"word": "مزبدة", "strongs": "G1890"},
{"word": "بخزيهم", "strongs": "G152"},
{"word": "نجوم", "strongs": "G792"},
{"word": "تائهة", "strongs": "G4107"},
{"word": "محفوظ", "strongs": "G5083"},
{"word": "لها", "strongs": "G846"},
{"word": "قتام", "strongs": "G2217"},
{"word": "الظلام", "strongs": "G4655"},
{"word": "الى", "strongs": "G1519"},
{"word": "الابد", "strongs": "G165"},
{"word": "وتنبأ", "strongs": "G4395"},
{"word": "عن", "strongs": "G0"},
{"word": "هؤلاء", "strongs": "G5125"},
{"word": "ايضا", "strongs": "G2532"},
{"word": "اخنوخ", "strongs": "G1802"},
{"word": "السابع", "strongs": "G1442"},
{"word": "من", "strongs": "G575"},
{"word": "ادم", "strongs": "G76"},
{"word": "قائلا", "strongs": "G3004"},
{"word": "هوذا", "strongs": "G2400"},
{"word": "قد", "strongs": "G0"},
{"word": "جاء", "strongs": "G2064"},
{"word": "الرب", "strongs": "G2962"},
{"word": "في", "strongs": "G1722"},
{"word": "ربوات", "strongs": "G3461"},
{"word": "قديسيه", "strongs": "G40"},
{"word": "ليصنع", "strongs": "G4160"},
{"word": "دينونة", "strongs": "G2920"},
{"word": "على", "strongs": "G2596"},
{"word": "الجميع", "strongs": "G3956"},
{"word": "ويعاقب", "strongs": "G1651"},
{"word": "جميع", "strongs": "G3956"},
{"word": "فجارهم", "strongs": "G763"},
{"word": "على", "strongs": "G4012"},
{"word": "جميع", "strongs": "G3956"},
{"word": "اعمال", "strongs": "G2041"},
{"word": "فجورهم", "strongs": "G763"},
{"word": "التي", "strongs": "G3739"},
{"word": "فجروا", "strongs": "G764"},
{"word": "بها", "strongs": "G0"},
{"word": "وعلى", "strongs": "G4012"},
{"word": "جميع", "strongs": "G3956"},
{"word": "الكلمات", "strongs": "G3056"},
{"word": "الصعبة", "strongs": "G4642"},
{"word": "التي", "strongs": "G3739"},
{"word": "تكلم", "strongs": "G2980"},
{"word": "بها", "strongs": "G0"},
{"word": "عليه", "strongs": "G2596"},
{"word": "خطاة", "strongs": "G268"},
{"word": "فجار", "strongs": "G765"}
];

const list2 = [
{"word": "هؤلاء", "strongs": "G3778"},
{"word": "هم", "strongs": "G1526"},
{"word": "مدمدمون", "strongs": "G1113"},
{"word": "متشكون", "strongs": "G3202"},
{"word": "سالكون", "strongs": "G4198"},
{"word": "بحسب", "strongs": "G2596"},
{"word": "شهواتهم", "strongs": "G1939"},
{"word": "وفمهم", "strongs": "G4750"},
{"word": "يتكلم", "strongs": "G2980"},
{"word": "بعظائم", "strongs": "G5236"},
{"word": "يحابون", "strongs": "G2296"},
{"word": "بالوجوه", "strongs": "G4383"},
{"word": "من", "strongs": "G0"},
{"word": "اجل", "strongs": "G5484"},
{"word": "المنفعة", "strongs": "G5622"},
{"word": "واما", "strongs": "G1161"},
{"word": "انتم", "strongs": "G5210"},
{"word": "ايها", "strongs": "G0"},
{"word": "الاحباء", "strongs": "G27"},
{"word": "فاذكروا", "strongs": "G3415"},
{"word": "الاقوال", "strongs": "G4487"},
{"word": "التي", "strongs": "G3588"},
{"word": "قيلت", "strongs": "G4302"},
{"word": "سابقا", "strongs": "G4302"},
{"word": "من", "strongs": "G5259"},
{"word": "رسل", "strongs": "G652"},
{"word": "ربنا", "strongs": "G2962"},
{"word": "يسوع", "strongs": "G2424"},
{"word": "المسيح", "strongs": "G5547"},
{"word": "فانهم", "strongs": "G3754"},
{"word": "قالوا", "strongs": "G3004"},
{"word": "لكم", "strongs": "G5213"},
{"word": "انه", "strongs": "G3754"},
{"word": "في", "strongs": "G1722"},
{"word": "الزمان", "strongs": "G5550"},
{"word": "الاخير", "strongs": "G2078"},
{"word": "سيكون", "strongs": "G1510"},
{"word": "قوم", "strongs": "G0"},
{"word": "مستهزئون", "strongs": "G1703"},
{"word": "سالكين", "strongs": "G4198"},
{"word": "بحسب", "strongs": "G2596"},
{"word": "شهوات", "strongs": "G1939"},
{"word": "فجورهم", "strongs": "G763"},
{"word": "هؤلاء", "strongs": "G3778"},
{"word": "هم", "strongs": "G1526"},
{"word": "المعتزلون", "strongs": "G592"},
{"word": "بانفسهم", "strongs": "G1438"},
{"word": "نفسانيون", "strongs": "G5591"},
{"word": "لا", "strongs": "G3361"},
{"word": "روح", "strongs": "G4151"},
{"word": "لهم", "strongs": "G2192"},
{"word": "واما", "strongs": "G1161"},
{"word": "انتم", "strongs": "G5210"},
{"word": "ايها", "strongs": "G0"},
{"word": "الاحباء", "strongs": "G27"},
{"word": "فابنوا", "strongs": "G2026"},
{"word": "انفسكم", "strongs": "G1438"},
{"word": "على", "strongs": "G1909"},
{"word": "ايمانكم", "strongs": "G4102"},
{"word": "الاقدس", "strongs": "G40"},
{"word": "مصلين", "strongs": "G4336"},
{"word": "في", "strongs": "G1722"},
{"word": "الروح", "strongs": "G4151"},
{"word": "القدس", "strongs": "G40"},
{"word": "واحفظوا", "strongs": "G5083"},
{"word": "انفسكم", "strongs": "G1438"},
{"word": "في", "strongs": "G1722"},
{"word": "محبة", "strongs": "G26"},
{"word": "الله", "strongs": "G2316"},
{"word": "منتظرين", "strongs": "G4327"},
{"word": "رحمة", "strongs": "G1656"},
{"word": "ربنا", "strongs": "G2962"},
{"word": "يسوع", "strongs": "G2424"},
{"word": "المسيح", "strongs": "G5547"},
{"word": "للحياة", "strongs": "G2222"},
{"word": "الابدية", "strongs": "G166"},
{"word": "وارحموا", "strongs": "G1653"},
{"word": "البعض", "strongs": "G3739"},
{"word": "مميزين", "strongs": "G1252"},
{"word": "وخلصوا", "strongs": "G4982"},
{"word": "البعض", "strongs": "G3739"},
{"word": "بالخوف", "strongs": "G5401"},
{"word": "مختطفين", "strongs": "G726"},
{"word": "من", "strongs": "G1537"},
{"word": "النار", "strongs": "G4442"},
{"word": "مبغضين", "strongs": "G3404"},
{"word": "حتى", "strongs": "G2532"},
{"word": "الثوب", "strongs": "G5509"},
{"word": "المدنس", "strongs": "G4695"},
{"word": "من", "strongs": "G575"},
{"word": "الجسد", "strongs": "G4561"},
{"word": "والقادر", "strongs": "G1410"},
{"word": "ان", "strongs": "G0"},
{"word": "يحفظكم", "strongs": "G5442"},
{"word": "غير", "strongs": "G0"},
{"word": "عاثرين", "strongs": "G679"},
{"word": "ويوقفكم", "strongs": "G2476"},
{"word": "امام", "strongs": "G2714"},
{"word": "مجده", "strongs": "G1391"},
{"word": "بلا", "strongs": "G0"},
{"word": "عيب", "strongs": "G299"},
{"word": "في", "strongs": "G1722"},
{"word": "الابتهاج", "strongs": "G20"},
{"word": "الاله", "strongs": "G2316"},
{"word": "الحكيم", "strongs": "G4680"},
{"word": "الوحيد", "strongs": "G3441"},
{"word": "مخلصنا", "strongs": "G4990"},
{"word": "له", "strongs": "G0"},
{"word": "المجد", "strongs": "G1391"},
{"word": "والعظمة", "strongs": "G3172"},
{"word": "والقدرة", "strongs": "G2904"},
{"word": "والسلطان", "strongs": "G1849"},
{"word": "الان", "strongs": "G3568"},
{"word": "والى", "strongs": "G1519"},
{"word": "كل", "strongs": "G3956"},
{"word": "الدهور", "strongs": "G165"},
{"word": "امين", "strongs": "G281"}
];

const API_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qdHNvcXhmdXdwY213bnBuYWJvIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4NzAyNzc3NiwiZXhwIjoyMTAyNjAzNzc2fQ.jZJQLfEUjropwUsYfBVUkMlWc-p343_wpD4fNTkPgbA';

async function main() {
  const versesRes = await fetch('https://ojtsoqxfuwpcmwnpnabo.supabase.co/rest/v1/verses?book_id=eq.65&select=id,chapter_num,verse_num,text_avd_ar&order=verse_num.asc', {
    headers: { 'apikey': API_KEY, 'Authorization': `Bearer ${API_KEY}` }
  });
  const verses = await versesRes.json();
  
  let outMappings = [];
  
  // Verse 1 to 15
  let fIndex1 = 0;
  for (let v of verses) {
    if (v.verse_num > 15) break;
    
    let cleanText = v.text_avd_ar.replace(/[.,:;؟!`"'\(\)\[\]\{\}]/g, '').replace(/[\u064B-\u065F\u0640]/g, '');
    let words = cleanText.split(/\s+/).filter(w => w.trim().length > 0);
    
    if (v.verse_num === 11) {
      words.splice(4, 0, "في"); // AI added this
    }
    
    for (let i=0; i<words.length; i++) {
      let fWord = list1[fIndex1];
      outMappings.push({
        verse_id: v.id,
        ar_word: words[i], 
        strongs_id: fWord.strongs === "G0" ? null : fWord.strongs,
        ar_word_position: i + 1,
        orig_word_position: i + 1,
        orig_word: '---',
        orig_word_lang: 'greek',
        is_verified: true
      });
      fIndex1++;
    }
  }

  // Verse 16 to 25
  let fIndex2 = 0;
  for (let v of verses) {
    if (v.verse_num <= 15) continue;
    
    let cleanText = v.text_avd_ar.replace(/[.,:;؟!`"'\(\)\[\]\{\}]/g, '').replace(/[\u064B-\u065F\u0640]/g, '');
    let words = cleanText.split(/\s+/).filter(w => w.trim().length > 0);
    
    if (v.verse_num === 17) {
       // AVD: التي قالها سابقا رسل
       // AI: التي قيلت سابقا من رسل
       words.splice(5, 1, "قيلت");
       words.splice(7, 0, "من");
    }
    if (v.verse_num === 20) {
       // AVD: مصلّين in some? no, simple clean text
    }
    
    for (let i=0; i<words.length; i++) {
      if (fIndex2 >= list2.length) break;
      let fWord = list2[fIndex2];
      outMappings.push({
        verse_id: v.id,
        ar_word: words[i],
        strongs_id: fWord.strongs === "G0" ? null : fWord.strongs,
        ar_word_position: i + 1,
        orig_word_position: i + 1,
        orig_word: '---',
        orig_word_lang: 'greek',
        is_verified: true
      });
      fIndex2++;
    }
  }

  console.log(`Prepared ${outMappings.length} words. Attempting UPSERT to Supabase...`);
  
  // Upsert in batches of 100
  for (let i=0; i<outMappings.length; i+=100) {
    const chunk = outMappings.slice(i, i+100);
    const res = await fetch('https://ojtsoqxfuwpcmwnpnabo.supabase.co/rest/v1/word_mappings', {
      method: 'POST',
      headers: {
        'apikey': API_KEY,
        'Authorization': `Bearer ${API_KEY}`,
        'Content-Type': 'application/json',
        'Prefer': 'resolution=merge-duplicates'
      },
      body: JSON.stringify(chunk)
    });
    if (!res.ok) {
      console.error(await res.text());
    } else {
      console.log(`Inserted chunk ${i/100 + 1}`);
    }
  }
  console.log("DONE JUDE UPLOAD!");
}
main();
